import { derived, type Readable } from 'svelte/store';

import { exports } from '$lib/stores/Export';
import { filterTree, genomicFilters } from '$lib/stores/Filter';

export interface CohortContents {
  /**
   * One identity per filter, genomic filter and added variable, derived from that item's own
   * query content. Two items with the same identity are the same item, so an identity that
   * was not there before is something the cohort gained - which is the question the panel
   * actually needs answered, and one a count cannot answer.
   */
  items: string[];
  /** How the filters are combined: the operators, the grouping, and the order within it. */
  structure: string;
}

type QueryNode = Record<string, unknown>;

/**
 * A field belongs here when it can differ between two reads that describe the same query.
 * That is the whole rule, and it is the only rule in this file.
 *
 * - `uuid` is regenerated by every mutator in `stores/Filter.ts` before it writes, including
 *   the ones that changed nothing - so `removeUnallowedFilters` with nothing unallowed would
 *   otherwise read as an edit. On a group it is worse: `id` is a live getter over `uuid`, so
 *   excluding `uuid` alone still leaks it.
 * - `searchResult` is the dictionary row a filter was built from, and `enrichFilterDetails`
 *   patches `table` and `study` onto a filter that is *already in the tree*, in place, with
 *   no write to `filterTree` - so a panel would see one identity while mounted and a
 *   different one the next time anything looked.
 * - `parent` back-references its group, so reading it is both a cycle and a restatement of
 *   structure that `structureOf` already carries.
 *
 * Everything else an item holds is kept, and that includes fields no query is built from -
 * `description`, `variableName`, `display`, `allowFiltering`. They stay because they cannot
 * differ between two reads of the same query: each is written once when the item is created
 * and never touched again. Keeping them is also the safe default, since a filter type that
 * gains a new value field is then covered without anyone remembering to come here.
 *
 * The invariant, for whoever is tempted to break it next: if you patch a field on an item
 * that is already in a store, either route the write through that store's `set` or add the
 * field here. `enrichFilterDetails` is the one place that does neither.
 */
const NOT_PART_OF_AN_IDENTITY = new Set(['parent', 'uuid', 'searchResult']);

/**
 * Canonical JSON for one item. Object keys are sorted at every depth, so two producers that
 * assign the same fields in a different order - a filter built by `models/Filter.svelte` and
 * the same filter read back out of sessionStorage by `LogicTree.deserialize` - agree. Array
 * order is preserved, because there it carries meaning.
 *
 * The exclusions above apply at every depth as well, which is also what makes this safe
 * against the `parent` cycle.
 */
function identityOf(item: object): string {
  return JSON.stringify(canonical(item));
}

function canonical(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(canonical);
  if (value === null || typeof value !== 'object') return value;
  const source = value as QueryNode;
  const shape: QueryNode = {};
  for (const key of Object.keys(source).sort()) {
    if (NOT_PART_OF_AN_IDENTITY.has(key)) continue;
    shape[key] = canonical(source[key]);
  }
  return shape;
}

/**
 * The filter tree with every group reduced to its operator and every leaf to its identity. A
 * group contributes nothing else: the rest of one is either constant or bookkeeping, since
 * `createFilterGroup` mints a fresh `uuid` for every group it builds and `id` is a getter
 * over that `uuid`.
 *
 * Genomic filters and added variables have no structure - they are flat lists, and reordering
 * one is not a change to the query.
 */
function structureOf(node: QueryNode): unknown {
  if (Array.isArray(node.children)) {
    return {
      operator: node.operator,
      children: node.children.map((child) => structureOf(child as QueryNode)),
    };
  }
  return identityOf(node);
}

/**
 * The three stores that decide what the cohort summary panel's body has to show, reduced to
 * the two facts the panel needs and offered as one subscription.
 *
 * Identities are tagged by which store they came from, so a concept path in one can never be
 * mistaken for the same text in another.
 */
export const cohortContents: Readable<CohortContents> = derived(
  [filterTree, genomicFilters, exports],
  ([$filterTree, $genomicFilters, $exports]) => ({
    items: [
      ...$filterTree.leafNodes.map((filter) => `filter:${identityOf(filter)}`),
      ...$genomicFilters.map((filter) => `genomic:${identityOf(filter)}`),
      ...$exports.map((exported) => `variable:${identityOf(exported)}`),
    ],
    structure: JSON.stringify(structureOf($filterTree.root as unknown as QueryNode)),
  }),
);
