import { derived, type Readable } from 'svelte/store';

import { exports } from '$lib/stores/Export';
import { filterTree, genomicFilters } from '$lib/stores/Filter';

export interface CohortContents {
  /**
   * One identity per filter, genomic filter and added variable: a canonical snapshot of that
   * item. Two items with the same identity hold the same content - where they sit relative to
   * each other is `structure`, not part of an identity - so an identity the cohort holds more
   * of than it did is something it gained, which is the question the panel needs answered and
   * one a total cannot answer.
   *
   * Duplicates are kept. Nothing dedupes phenotypic filters, so two of them can hold the
   * same content and therefore the same identity, and the consumer counts rather than
   * collecting into a set.
   */
  items: string[];
  /** How the filters are combined: the operators, the grouping, and the order within it. */
  structure: string;
}

type QueryNode = Record<string, unknown>;

/**
 * An identity is a snapshot of the item, so what is excluded is what is not part of the
 * item: the token the app tracks it by, the link to whatever is holding it, and the record it
 * was built from. Each of the three below is the app's bookkeeping *about* an item rather
 * than content *of* one, and that is the whole criterion - the members follow from it.
 *
 * It also happens to be what makes the snapshot stable, which is why these three and not
 * some other three:
 *
 * - `uuid` is regenerated by every mutator in `stores/Filter.ts` before it writes, including
 *   the ones that changed nothing - so `removeUnallowedFilters` with nothing unallowed would
 *   otherwise read as an edit. On a group it is worse: `id` is a live getter over `uuid`, so
 *   dropping `uuid` alone still leaks it, which is why `structureOf` reduces groups instead.
 * - `searchResult` is the dictionary row a filter was built from, and `enrichFilterDetails`
 *   patches `table` and `study` onto a filter that is *already in the tree*, in place, with
 *   no write to `filterTree` - so a panel would see one snapshot while mounted and a
 *   different one the next time anything looked.
 * - `parent` back-references its group, so reading it is both a cycle and a restatement of
 *   what `structureOf` already carries.
 *
 * Everything an item holds about itself stays, including fields no query is built from -
 * `display`, `description`, `variableName`, `allowFiltering`. A snapshot is not query
 * identity and is not meant to be: a dataset restore rebuilds an added variable from a saved
 * query rather than from a search row, and can hand back a different `display` for the same
 * concept path. Treating that as a new item is the intended reading, because the panel would
 * show it differently - and erring that way costs a panel that opens when it need not,
 * rather than one that hides something the user just restored.
 *
 * The invariant, for whoever is tempted to break it next: if you patch a field on an item
 * that is already in a store, either route the write through that store's `set` or add the
 * field here. `enrichFilterDetails` is the one place that does neither.
 */
const NOT_PART_OF_AN_IDENTITY = new Set(['parent', 'uuid', 'searchResult']);

/**
 * Canonical JSON for one item. Object keys are sorted at every depth, so two producers that
 * assign the same fields in a different order - a filter built by `models/Filter.svelte` and
 * the same filter read back out of sessionStorage by `LogicTree.deserialize` - agree. Array
 * order is preserved, because there it carries meaning.
 *
 * The exclusions above apply at every depth as well, which is also what makes this safe
 * against the `parent` cycle.
 */
function identityOf(item: object): string {
  return JSON.stringify(canonical(item));
}

function canonical(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(canonical);
  if (value === null || typeof value !== 'object') return value;
  const source = value as QueryNode;
  const shape: QueryNode = {};
  for (const key of Object.keys(source).sort()) {
    if (NOT_PART_OF_AN_IDENTITY.has(key)) continue;
    shape[key] = canonical(source[key]);
  }
  return shape;
}

/**
 * The filter tree with every group reduced to its operator and every leaf to its identity. A
 * group contributes nothing else: the rest of one is either constant or bookkeeping, since
 * `createFilterGroup` mints a fresh `uuid` for every group it builds and `id` is a getter
 * over that `uuid`.
 *
 * Child order is part of what this returns, so reordering filters within the tree does change
 * `structure` and does open the panel - which is what the builder's drag-and-drop reorder
 * relies on. Genomic filters and added variables are the exception: they are flat lists with
 * no structure of their own, so the order they happen to sit in is not compared at all.
 */
function structureOf(node: QueryNode): unknown {
  if (Array.isArray(node.children)) {
    return {
      operator: node.operator,
      children: node.children.map((child) => structureOf(child as QueryNode)),
    };
  }
  return identityOf(node);
}

/**
 * The three stores that decide what the cohort summary panel's body has to show, reduced to
 * the two facts the panel needs and offered as one subscription.
 *
 * Identities are tagged by which store they came from, so a concept path in one can never be
 * mistaken for the same text in another.
 */
export const cohortContents: Readable<CohortContents> = derived(
  [filterTree, genomicFilters, exports],
  ([$filterTree, $genomicFilters, $exports]) => ({
    items: [
      ...$filterTree.leafNodes.map((filter) => `filter:${identityOf(filter)}`),
      ...$genomicFilters.map((filter) => `genomic:${identityOf(filter)}`),
      ...$exports.map((exported) => `variable:${identityOf(exported)}`),
    ],
    structure: JSON.stringify(structureOf($filterTree.root as unknown as QueryNode)),
  }),
);
