import { derived, type Readable } from 'svelte/store';

import { exports } from '$lib/stores/Export';
import { filterTree, genomicFilters } from '$lib/stores/Filter';

export interface CohortContents {
  /** How many filters, genomic filters and added variables the cohort holds. */
  size: number;
  /**
   * A canonical description of the query the cohort expresses: which concepts, which values,
   * which operators, in which grouping. Two reads that produce the same string describe the
   * same query.
   */
  signature: string;
}

type QueryNode = Record<string, unknown>;

/**
 * Bookkeeping and display, not query - and both would break the signature if they reached it.
 *
 * `uuid` is regenerated by every mutator in `stores/Filter.ts` before it writes the store,
 * including the ones that change nothing, so including it would make a no-op look like an
 * edit. `searchResult` is the dictionary row a filter was built from, and
 * `enrichFilterDetails` patches `searchResult.table` and `searchResult.study` onto a filter
 * that is *already in the tree*, in place, without ever calling `filterTree.set` - so
 * including it would make an unchanged cohort read differently the next time anything looked,
 * which is the one thing the signature exists to rule out.
 *
 * The test for whether a field belongs here is whether `utilities/QueryBuilder` reads it.
 * It reads neither of these.
 */
const NOT_PART_OF_THE_QUERY = new Set(['parent', 'uuid', 'searchResult']);

/**
 * Projects a filter, a group or an added variable onto the part of itself that defines the
 * query.
 *
 * A group contributes its operator and the order of what it holds, and nothing else. The rest
 * of a group is either constant (`filterType`, `displayType`, `variableName`) or bookkeeping:
 * `createFilterGroup` mints a fresh `uuid` for every group it builds, and `id` is a getter
 * over that `uuid`, so `removeUnallowedFilters` regenerating the root's uuid would otherwise
 * read as an edit even when it removed nothing.
 *
 * A leaf keeps everything else it has, so a filter type that gains a new value field is
 * covered without anyone remembering to list it here. Keys are sorted so the string does not
 * depend on the order a node's properties happened to be assigned in - a filter built by
 * `models/Filter.svelte` and the same filter read back out of sessionStorage by
 * `LogicTree.deserialize` must agree.
 */
function queryShape(node: QueryNode): QueryNode {
  if (Array.isArray(node.children)) {
    return {
      operator: node.operator,
      children: node.children.map((child) => queryShape(child as QueryNode)),
    };
  }
  const shape: QueryNode = {};
  for (const key of Object.keys(node).sort()) {
    if (NOT_PART_OF_THE_QUERY.has(key)) continue;
    shape[key] = node[key];
  }
  return shape;
}

const shapeOf = (node: object) => queryShape(node as QueryNode);

/**
 * The three stores that decide what the cohort summary panel's body has to show, reduced to
 * the two facts the panel needs and offered as one subscription.
 *
 * Keyed sections rather than a concatenation, so a concept path in one can never be mistaken
 * for a value in another.
 */
export const cohortContents: Readable<CohortContents> = derived(
  [filterTree, genomicFilters, exports],
  ([$filterTree, $genomicFilters, $exports]) => ({
    size: $filterTree.leafNodes.length + $genomicFilters.length + $exports.length,
    signature: JSON.stringify({
      filters: shapeOf($filterTree.root),
      genomic: $genomicFilters.map(shapeOf),
      variables: $exports.map(shapeOf),
    }),
  }),
);
