[supervisord]
nodaemon=true
logfile=/dev/fd/1
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:httpd]
command=httpd-foreground
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:npm]
command=npm run dev
directory=/app
stdout_logfile=./logs/stdout.log
stdout_logfile_maxbytes=1MB
redirect_stderr=true
stdout_events_enabled=true
