export const datasets = [
  {
    // Active
    uuid: '3fc5301a-aa58-4abf-bcec-369d4ed9fdd2',
    user: 'test@user',
    name: 'active demo',
    archived: false,
    query: {
      uuid: '6104ee94-1b0c-44cb-bed2-08c95d1d63ee',
    },
    metadata: {},
  },
  {
    // Archived
    uuid: '73952c80-641c-4f35-a527-ebfb3c55e02b',
    user: 'test@user',
    name: 'inactive demo',
    archived: true,
    query: {
      uuid: '853c2c35-f665-462e-8775-aa07121ae3dc',
    },
    metadata: {},
  },
];

export const user = {
  uuid: '1234',
  email: 'test@pic-sure.org',
  privileges: ['user'],
  // expired token
  token:
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwiZW1haWwiOiJ0ZXN0QHBpYy1zdXJlLm9yZyIsImV4cCI6MTYxMjE2NDk4MiwiaWF0IjoxNjA5NTcyOTgyfQ.kzaW-ZkhCPlTgdGQQAz_CA1ZB80PpZ5aiRa2lj46hbw',
  acceptedTOS: true,
};

export const searchResultPath = '*/**/picsure/search/bf638674-053b-46c4-96a1-4cd6c8395248';
export const searchResults = {
  results: {
    phenotypes: {
      '\\some\\test\\lab1\\': {
        name: '\\some\\test\\lab1\\',
        categorical: true,
        patientCount: 9499,
        categoryValues: [
          'name',
          'test',
          'value45364',
          '34234234234234',
          'test2',
          'value334535352',
          'A very looooooooooooong value for testing to test really long values with in the ui and other stuff like that, we need a very loooooooong wooooooooooooord to test with.',
          'a',
          '22',
          'value1',
          'value2',
          'value3',
          'value4',
          'value5',
          'value6',
          'value7',
          'value8',
          'value9',
          'value10',
          'value11',
          'value12',
          'value13',
          'value14',
          'value15',
          'value16',
          'value17',
          'value18',
          'value19',
          'value20',
          'value21',
          'value22',
          'value23',
          'value24',
          'value25',
          'value26',
          'value27',
          'value28',
          'value29',
          'value30',
          'value31',
          'value32',
          'value33',
          'value34',
          'value35',
          'value36',
          'value37',
          'value38',
          'value39',
          'value40',
          'value41',
          'value42',
          'value43',
          'value44',
          'value45',
          'value46',
          'value47',
          'value48',
          'value49',
          'value50',
          'value51',
          'value52',
          'value53',
          'value54',
          'value55',
          'value56',
          'value57',
          'value58',
          'value59',
          'value60',
        ],
      },
      '\\some\\test\\lab2\\': {
        name: '\\some\\test\\lab2\\',
        categorical: true,
        patientCount: 8971,
        categoryValues: ['value1', 'value2', 'value3'],
      },
      '\\some\\test\\numerical\\': {
        name: '\\some\\test\\numerical\\',
        categorical: false,
        patientCount: 222,
        min: 11,
        max: 99,
      },
    },
  },
};
