export interface LogEvent {
  _time?: string;
  event_type: string;
  action?: string;
  session_id?: string;
  user_id?: string;
  user_id_provider?: string;
  user_name?: string;
  user_email?: string;
  user_country_name?: string;
  user_org?: string;
  nih_ico?: string;
  cadr_name?: string;
  eRA_commons_id?: string;
  user_permission_group?: string;
  user_uuid?: string;
  user_subject?: string;
  idp?: string;
  logged_in?: boolean;
  roles?: string[];
  app?: string;
  platform?: string;
  environment?: string;
  client_type?: string;
  hostname?: string;
  request_id?: string;
  method?: string;
  url?: string;
  query_string?: string;
  src_ip?: string;
  dest_ip?: string;
  dest_port?: number;
  http_user_agent?: string;
  http_content_type?: string;
  status?: number;
  bytes?: number;
  duration?: number;
  referrer?: string;
  metadata?: Record<string, unknown>;
  error?: { origin?: string; message?: string; [key: string]: unknown };
}
