import { describe, expect, it } from 'vitest';
import tourConfig from '$lib/assets/TourConfiguration.json';

// Hook names wired up in ExplorerTour.svelte's `functionMap`. An unmapped name here
// silently drops that step's custom behavior (falls back to default next/highlight
// handling) instead of erroring - keep this list in sync with that component.
const VALID_HOOKS = new Set([
  'disablePrevious',
  'clickElement',
  'clickElementThenNext',
  'addHighlightClass',
  'removeHighlightClass',
  'resetSearch',
  'applyFilterThenNext',
  'findAndSetFirstNonStigmatizedAvailableFilterThenNext',
]);

// The datatable only ever mints ids of these shapes (see Row.svelte /
// RemoteTable.svelte), always prefixed with the table name ("ExplorerTable"
// for the explorer search results table the tour walks through).
const DYNAMIC_ID_PATTERN = /^ExplorerTable-(table|row-\d+|active-row-\d+|row-\d+-col-\d+)$/;

// Fixed, page-level ids the tour also targets, none of which are generated per-row.
// Each value is the file it was confirmed to render in (not re-checked by this test).
const STATIC_IDS: Record<string, string> = {
  'explorer-search-box': 'src/lib/components/Searchbox.svelte',
  'facet-side-bar': 'src/lib/components/explorer/Explorer.svelte',
  'sidebar-right': 'src/routes/(picsure)/+layout.svelte',
  'advanced-query-btn': 'src/lib/components/explorer/results/Filters.svelte',
  'explorer-distributions-btn': 'src/lib/components/explorer/results/ResultsPanel.svelte',
  // Generated by Navigation.svelte's getId() from the /help route entry in
  // src/lib/routes.ts (`nav-link` + path.replaceAll('/', '-')).
  'nav-link-help': 'src/lib/routes.ts',
};

// Classes the row/action-button markup actually renders (Row.svelte, Actions.svelte).
// `non-stigmatized-row` is the exception: added at runtime by ExplorerTour.svelte's
// findAndSetFirstNonStigmatizedAvailableFilterThenNext hook, not by markup.
const KNOWN_CLASSES = new Set([
  'expandable-row',
  'non-stigmatized-row',
  'row-action-info',
  'row-action-filter',
  'row-action-hierarchy',
  'row-action-export',
]);

type Step = {
  element: string;
  onHighlightStarted?: string;
  dependsOnFeature?: string;
  popover: {
    title: string;
    description: string;
    onPrevClick?: string;
    onNextClick?: string;
  };
};

type Tour = {
  searchTerm: string;
  title: string;
  description: string;
  steps: Step[];
};

const tours = tourConfig as unknown as Record<string, Tour>;

function idsIn(selector: string): string[] {
  return [...selector.matchAll(/#([\w-]+)/g)].map((m) => m[1]);
}

function classesIn(selector: string): string[] {
  return [...selector.matchAll(/\.([\w-]+)/g)].map((m) => m[1]);
}

describe('TourConfiguration.json', () => {
  it('defines at least one tour', () => {
    expect(Object.keys(tours).length).toBeGreaterThan(0);
  });

  describe.each(Object.keys(tours))('%s', (tourName) => {
    const tour = tours[tourName];

    it('has the required top-level fields', () => {
      expect(tour.searchTerm).toBeTruthy();
      expect(tour.title).toBeTruthy();
      expect(tour.description).toBeTruthy();
      expect(tour.steps.length).toBeGreaterThan(0);
    });

    it.each(tour.steps.map((step, index) => [index, step] as const))(
      'step %i has a well-formed popover',
      (_index, step) => {
        expect(step.popover.title).toBeTruthy();
        expect(step.popover.description).toBeTruthy();
      },
    );

    it.each(tour.steps.map((step, index) => [index, step] as const))(
      'step %i only targets known, page-unique ids',
      (_index, step) => {
        for (const id of idsIn(step.element)) {
          const isDynamic = DYNAMIC_ID_PATTERN.test(id);
          const isStatic = Object.hasOwn(STATIC_IDS, id);
          expect(
            isDynamic || isStatic,
            `"#${id}" in "${step.element}" doesn't match the ExplorerTable-* row/col ` +
              `convention and isn't a recognized static id. If the underlying component ` +
              `changed its id scheme, update the selector here to match.`,
          ).toBe(true);
        }
      },
    );

    it.each(tour.steps.map((step, index) => [index, step] as const))(
      'step %i only targets known classes',
      (_index, step) => {
        for (const cls of classesIn(step.element)) {
          expect(
            KNOWN_CLASSES.has(cls),
            `".${cls}" in "${step.element}" isn't a class the datatable/action markup renders.`,
          ).toBe(true);
        }
      },
    );

    it.each(tour.steps.map((step, index) => [index, step] as const))(
      'step %i does not use brittle attribute selectors (e.g. button[title=...])',
      (_index, step) => {
        expect(step.element).not.toMatch(/\[title=/);
      },
    );

    it.each(tour.steps.map((step, index) => [index, step] as const))(
      'step %i references only real driver.js hooks',
      (_index, step) => {
        const referenced = [
          step.onHighlightStarted,
          step.popover.onPrevClick,
          step.popover.onNextClick,
        ].filter((name): name is string => Boolean(name));
        for (const name of referenced) {
          expect(
            VALID_HOOKS.has(name),
            `"${name}" is not in ExplorerTour.svelte's functionMap`,
          ).toBe(true);
        }
      },
    );

    it.each(tour.steps.map((step, index) => [index, step] as const))(
      'step %i has a non-empty dependsOnFeature when present',
      (_index, step) => {
        if (Object.hasOwn(step, 'dependsOnFeature')) {
          expect(step.dependsOnFeature).toMatch(/^[\w]+\.[\w.]+$/);
        }
      },
    );
  });
});
