name: Tests
on:
  push:
    branches: [main, dev, workflows/docker]
  pull_request:
    branches: [main, dev, workflows/docker]
  schedule:
    - cron: 33 7 * * 1,3,5

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Create mock env file
        run: cp .env.test .env
      - name: Create mock host file
        run: touch httpd-vhosts.conf
      - name: Create mock cert dir
        run: mkdir cert
      - name: Build docker images
        run: docker build -f Dockerfile -t picsureui .
