name: Label Checker
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:
  check_labels:
    name: Check labels
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker@sha256:f6cc01b7dff9694dbf7a8db96e251e7c3fd1fd8c6fb59a3810bdd6955ff82522 # v1.6.65
        with:
          any_of: breaking-change,enhancement,bug,documentation,ignore-for-release,dependencies
          repo_token: ${{ secrets.GITHUB_TOKEN }}
