name: Tests
on:
  push:
    branches: [main, release]
  pull_request:
    branches: [main, release]
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Use PNPM 10
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Sync SvelteKit
        run: pnpm svelte-kit sync
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Check Playwright versions
        run: pnpm ls @playwright/test || true

      - name: Run linting tests
        run: pnpm run lint
      - name: Run Playwright tests
        run: pnpm run test

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
